# Generated by Django 4.2.23 on 2025-06-26 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataParamsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_size', models.IntegerField()),
                ('ratio_train', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'data_param',
                'verbose_name_plural': 'data_params',
            },
        ),
        migrations.CreateModel(
            name='HyperparamsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation', models.CharField(max_length=10)),
                ('learning_rate', models.FloatField()),
                ('epochs', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'hyperparam',
                'verbose_name_plural': 'hyperparams',
            },
        ),
        migrations.CreateModel(
            name='AnnModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_file', models.CharField(blank=True, max_length=100, null=True)),
                ('arquitecture', models.CharField(max_length=20)),
                ('loss', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('data_params', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mnist_app.dataparamsmodel')),
                ('hyperparams', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mnist_app.hyperparamsmodel')),
            ],
            options={
                'verbose_name': 'ann',
                'verbose_name_plural': 'anns',
            },
        ),
    ]
